  - name: Playbook
    hosts: all
    become: yes
    tasks:
      - name: Start the instance if not running
        amazon.aws.ec2_instance:
          instance_ids: "{{ aws_instance_id }}"
          region: us-east-1
          state: running
        register: result
      - debug:
          var: result