  - name: "Start instance"
    hosts: localhost
    connection: local
    gather_facts: false
    vars:
      ansible_connection: local
    tasks:
      - name: Start the instance if not running
        delegate_to: localhost
        amazon.aws.ec2_instance:
          instance_ids: "{{ aws_instance_id }}"
          region: us-east-1
          state: running
          wait: True
        register: result
      - debug:
          var: result
  - name: Playbook
    hosts: all
    become: yes
    tasks:
      - name: Wait for system to become reachable over WinRM
        wait_for_connection:
          timeout: 900
      - name: Get hostname
        shell: echo $HOSTNAME
        register: result
      - debug:
          var: result